### ISSUE TITLE
This project got excluded from hacktoberfest 2021.

### ISSUE THREAD

**Issue by akash-rajak** [Opensourcecontri/Hacktoberfest-2021#365]
![image](https://user-images.githubusercontent.com/57003737/137343264-38fa3ade-a21d-4178-aa4b-9de6304b0f61.png)

**Comment by Opensourcecontri** [comment]
Please, provide the related PR to your project.

**Comment by akash435** [comment]
> Please, provide the related PR to your project.

PR #214

**Comment by Opensourcecontri** [comment]
I’ve added extra labels

**Comment by Aarush2k1** [comment]
same #178 #198

**Comment by akash435** [comment]
> @akash435 Added extra labels to one of your PR, Let me know, if it works or not….!
still excluded, I think once excluded, they don't include that project again, for me it happened other projects also.
